version: '3'

volumes:
  dados:
    driver: local

services:
  proxy:
    image: nginx
    ports:
      - 8000:80
    command: [nginx-debug, '-g', 'daemon off;']
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web
    restart: always

  web:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
    restart: always

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - dados:/var/lib/postgresql/data
    restart: always
